export const PRODUCTS_API_URL = "https://tn5e0l3yok.execute-api.us-west-1.amazonaws.com/dev/api/v2/AllProducts"
export const GET_PRODUCT_API_URL = "https://tn5e0l3yok.execute-api.us-west-1.amazonaws.com/dev/api/v2/Products"
export const CREATE_BOM_API_URL = "https://tn5e0l3yok.execute-api.us-west-1.amazonaws.com/dev/api/v2/ImportFile"
export const GET_BOM_API_URL = "https://tn5e0l3yok.execute-api.us-west-1.amazonaws.com/dev/api/v2/GetBOM"
export const RUN_CTB_API_URL = "https://tn5e0l3yok.execute-api.us-west-1.amazonaws.com/dev/api/v2/RunCTB"
export const RUN_ORDER_LIST_API_URL = "https://tn5e0l3yok.execute-api.us-west-1.amazonaws.com/dev/api/v2/RunOrderList"
export const DELETE_PRODUCT_API_URL = "https://tn5e0l3yok.execute-api.us-west-1.amazonaws.com/dev/api/v2/Delete"
